version: '3'
services:
  registry:
    restart: always
    image: registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/certs/ca.crt
      REGISTRY_HTTP_TLS_KEY: /etc/certs/ca.key
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /app_data
    
    volumes:
      - /root/auth:/auth
      - /app_data:/app_data
      - /etc/certs:/etc/certs
