# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "registry" do |registry|
  registry.vm.box = "cigeek/debian96"
  registry.vm.hostname = "reg-server"
  registry.vm.network "private_network", ip: "192.168.33.89" 
# Creating an addtional disk to store app data. Needs to be formatted
  registry.vm.provider "virtualbox" do |v|
    file_to_disk = 'disk.vdi'
    #v.gui = true
    unless File.exist?(file_to_disk)
    v.customize ['createhd', '--filename', file_to_disk, '--size', 20 * 1024]
    end
	v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
	end 
    registry.vm.provision "shell", path: "provisioner/install-reg-server-setup.sh"
#  run: "always",
  #privileged: true
end
config.vm.define "client" do |client|
  client.vm.box = "cigeek/debian96"
  client.vm.hostname = "reg-client"
  client.vm.network "private_network", ip: "192.168.33.90"
  client.vm.provision "shell", path: "provisioner/install-reg-client-setup.sh"
  end
  end